// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwbkddRWcP2_4w1d7cqxp3k4Z1PRiu3s',
    appId: '1:79696661404:web:e6073e307367360da2d659',
    messagingSenderId: '79696661404',
    projectId: 'pillext',
    authDomain: 'pillext.firebaseapp.com',
    storageBucket: 'pillext.appspot.com',
    measurementId: 'G-DZVKK83ZTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9M5HD9PE8Rp1G-7agjXRLNGOrKz3jS-g',
    appId: '1:79696661404:android:d0478afefac1e5d3a2d659',
    messagingSenderId: '79696661404',
    projectId: 'pillext',
    storageBucket: 'pillext.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjK7RjhkmKkLSEfQsoHn1PDCSp9KzEZM',
    appId: '1:79696661404:ios:8e77676378918b49a2d659',
    messagingSenderId: '79696661404',
    projectId: 'pillext',
    storageBucket: 'pillext.appspot.com',
    iosClientId: '79696661404-nufvn9l55f2ue1ok36n7eh7tq3647ngj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillext',
  );
}
